version: "3"

tasks:
  generate:
    desc: "Generate go files from proto"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go